version: "1"
services:

  python:
    build: ./python
    container_name: python
    ports:
     - 5000:5000
    volumes:
     - ./python:/app
    env_file:
    - .env

  bbdd:
   build: ./postgres
   container_name: bbdd
   ports:
    - 5432:5432
   volumes:
    - ./postgres/data_bbdd:/var/lib/postgresql/data
   env_file:
    - .env